apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kompose.service.type: nodeport
    creationTimestamp: null
    labels:
      io.kompose.service: dokuwiki
    name: dokuwiki
  spec:
    ports:
    - name: "80"
      port: 80
      targetPort: 8080
    - name: "443"
      port: 443
      targetPort: 8080
    selector:
      io.kompose.service: dokuwiki
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    annotations:
      kompose.service.type: nodeport
    creationTimestamp: null
    name: dokuwiki
  spec:
    replicas: 1
    strategy:
      type: Recreate
    template:
      metadata:
        creationTimestamp: null
        labels:
          io.kompose.service: dokuwiki
      spec:
        containers:
        - image: kazuhisya/dokuwiki:latest
          name: dokuwiki
          ports:
          - containerPort: 8080
          resources: {}
          volumeMounts:
          - mountPath: /var/www/localhost/htdocs
            name: dokuwiki-data
        restartPolicy: Always
        volumes:
        - name: dokuwiki-data
          persistentVolumeClaim:
            claimName: dokuwiki-data
  status: {}
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    creationTimestamp: null
    labels:
      io.kompose.service: dokuwiki-data
    name: dokuwiki-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  status: {}
kind: List
metadata: {}
